export const ADMIN_GET_ALL_USERS_REQUEST = 'ADMIN_GET_ALL_USERS_REQUEST'
export const ADMIN_GET_ALL_USERS_SUCCESS = 'ADMIN_GET_ALL_USERS_SUCCESS'
export const ADMIN_GET_ALL_USERS_FAIL = 'ADMIN_GET_ALL_USERS_FAIL'

export const ADMIN_GET_USERS_BLOGS_REQUEST = 'ADMIN_GET_USERS_BLOGS_REQUEST'
export const ADMIN_GET_USERS_BLOGS_SUCCESS = 'ADMIN_GET_USERS_BLOGS_SUCCESS'
export const ADMIN_GET_USERS_BLOGS_FAIL = 'ADMIN_GET_USERS_BLOGS_FAIL'

export const ADMIN_EDIT_BLOG_REQUEST = 'ADMIN_EDIT_BLOG_REQUEST'
export const ADMIN_EDIT_BLOG_SUCCESS = 'ADMIN_EDIT_BLOG_SUCCESS'
export const ADMIN_EDIT_BLOG_FAIL = 'ADMIN_EDIT_BLOG_FAIL'

export const ADMIN_USER_BLOCK_UNBLOCK_REQUEST = 'ADMIN_USER_BLOCK_UNBLOCK_REQUEST'
export const ADMIN_USER_BLOCK_UNBLOCK_SUCCESS = 'ADMIN_USER_BLOCK_UNBLOCK_SUCCESS'
export const ADMIN_USER_BLOCK_UNBLOCK_FAIL = 'ADMIN_USER_BLOCK_UNBLOCK_FAIL'