export const ADD_BLOG_REQUEST = "ADD_BLOG_REQUEST"
export const ADD_BLOG_SUCCESS = "ADD_BLOG_SUCCESS"
export const ADD_BLOG_FAIL = "ADD_BLOG_FAIL"

export const GET_BLOG_REQUEST = 'GET_BLOG_REQUEST'
export const GET_BLOG_SUCCESS="GET_BLOG_SUCCESS"
export const GET_BLOG_FAIL="GET_BLOG_FAIL"


export const GET_ALL_BLOG_REQUEST = 'GET_ALL_BLOG_REQUEST'
export const GET_ALL_BLOG_SUCCESS="GET_ALL_BLOG_SUCCESS"
export const GET_ALL_BLOG_FAIL="GET_ALL_BLOG_FAIL"

export const SINGLE_BLOG_REQUEST = 'SINGLE_BLOG_REQUEST'
export const SINGLE_BLOG_SUCCESS = 'SINGLE_BLOG_SUCCESS'
export const SINGLE_BLOG_FAIL = 'SINGLE_BLOG_FAIL'

export const USER_BLOG_DELETE_REQUEST = 'USER_BLOG_DELETE_REQUEST'
export const USER_BLOG_DELETE_SUCCESS = 'USER_BLOG_DELETE_SUCCESS'
export const USER_BLOG_DELETE_FAIL = 'USER_BLOG_DELETE_FAIL'

export const USER_BLOG_UPDATE_REQUEST = 'USER_BLOG_UPDATE_REQUEST'
export const USER_BLOG_UPDATE_SUCCESS = 'USER_BLOG_UPDATE_SUCCESS'
export const USER_BLOG_UPDATE_FAIL = 'USER_BLOG_UPDATE_FAIL'